# coding: utf-8

"""
    null

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: null
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import footprint
from footprint.models.angle import Angle  # noqa: E501
from footprint.rest import ApiException


class TestAngle(unittest.TestCase):
    """Angle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAngle(self):
        """Test Angle"""
        # FIXME: construct object with mandatory attributes with example values
        # model = footprint.models.angle.Angle()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
