# coding: utf-8

"""
    null

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: null
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import footprint
from footprint import Configuration
from footprint.sciserver_client import SciServerClient
from footprint.api.editor_api import EditorApi  # noqa: E501
from footprint.rest import ApiException
from footprint.models import FootprintRegion, FootprintRegionRequest


class TestEditorApi(unittest.TestCase):
    """EditorApi unit test stubs"""

    def setUp(self):
        self.configuration = Configuration()
        self.configuration.proxy = 'http://localhost:8888'
        self.ssclient = SciServerClient(configuration=self.configuration)
        self.api = footprint.api.editor_api.EditorApi(self.ssclient)  # noqa: E501

    def tearDown(self):
        pass

    def test_combine_footprint_regions(self):
        """Test case for combine_footprint_regions

        Compute union, intersection or difference of regions.  # noqa: E501
        """
        pass

    def test_create_footprint_region(self):
        """Test case for create_footprint_region

        Create new region.  # noqa: E501
        """

        r1 = FootprintRegion()
        r1.region_string = 'CIRCLE J2000 10 10 10'

        self.api.create_footprint_region("test", FootprintRegionRequest(r1))

        r2 = self.api.get_footprint_region("test").region

        self.assertEqual(r1.region_string, r2.region_string)

        pass

    def test_delete_footprint(self):
        """Test case for delete_footprint

        Delete footprint and reset the editor.  # noqa: E501
        """
        pass

    def test_delete_footprint_region(self):
        """Test case for delete_footprint_region

        Delete a region.  # noqa: E501
        """
        pass

    def test_delete_footprint_regions(self):
        """Test case for delete_footprint_regions

        Deletes multiple regions.  # noqa: E501
        """
        pass

    def test_get_footprint(self):
        """Test case for get_footprint

        Returns the header information of the edited footprint  # noqa: E501
        """
        pass

    def test_get_footprint_outline(self):
        """Test case for get_footprint_outline

        Returns the outline of the footprint.  # noqa: E501
        """
        pass

    def test_get_footprint_outline_points(self):
        """Test case for get_footprint_outline_points

        Returns the points of the outline of the footprint.  # noqa: E501
        """
        pass

    def test_get_footprint_region(self):
        """Test case for get_footprint_region

        Returns the header information of a region.  # noqa: E501
        """
        pass

    def test_get_footprint_region_outline(self):
        """Test case for get_footprint_region_outline

        Returns the outline of the footprint.  # noqa: E501
        """
        pass

    def test_get_footprint_region_outline_points(self):
        """Test case for get_footprint_region_outline_points

        Returns the points of the outline of the footprint.  # noqa: E501
        """
        pass

    def test_get_footprint_region_shape(self):
        """Test case for get_footprint_region_shape

        Returns the shape description of the footprint region.  # noqa: E501
        """
        pass

    def test_get_footprint_region_thumbnail(self):
        """Test case for get_footprint_region_thumbnail

        Gets the thumbnail of a footprint region.  # noqa: E501
        """
        pass

    def test_get_footprint_shape(self):
        """Test case for get_footprint_shape

        Returns the shape description of the footprint.  # noqa: E501
        """
        pass

    def test_get_footprint_thumbnail(self):
        """Test case for get_footprint_thumbnail

        Gets the thumbnail of the footprint.  # noqa: E501
        """
        pass

    def test_list_footprint_regions(self):
        """Test case for list_footprint_regions

        List all regions.  # noqa: E501
        """
        pass

    def test_modify_footprint_region(self):
        """Test case for modify_footprint_region

        Modify a region.  # noqa: E501
        """
        pass

    def test_plot_footprint(self):
        """Test case for plot_footprint

        Plots the footprint  # noqa: E501
        """
        pass

    def test_plot_footprint_advanced(self):
        """Test case for plot_footprint_advanced

        Plots the footprint, with advanced parameters  # noqa: E501
        """
        pass

    def test_plot_footprint_region(self):
        """Test case for plot_footprint_region

        Plots a footprint region.  # noqa: E501
        """
        pass

    def test_plot_footprint_region_advanced(self):
        """Test case for plot_footprint_region_advanced

        Plots a footprint region.  # noqa: E501
        """
        pass

    def test_set_footprint_region_shape(self):
        """Test case for set_footprint_region_shape

        Upload a region shape binary or other representation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
