# coding: utf-8

"""
    null

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: null
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import footprint
from footprint.models.plot import Plot  # noqa: E501
from footprint.rest import ApiException


class TestPlot(unittest.TestCase):
    """Plot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlot(self):
        """Test Plot"""
        # FIXME: construct object with mandatory attributes with example values
        # model = footprint.models.plot.Plot()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
