# coding: utf-8

"""
    null

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: null
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import footprint
from footprint.models.color_theme import ColorTheme  # noqa: E501
from footprint.rest import ApiException


class TestColorTheme(unittest.TestCase):
    """ColorTheme unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testColorTheme(self):
        """Test ColorTheme"""
        # FIXME: construct object with mandatory attributes with example values
        # model = footprint.models.color_theme.ColorTheme()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
