# coding: utf-8

"""
    null

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: null
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import footprint
from footprint.api.footprint_api import FootprintApi  # noqa: E501
from footprint.rest import ApiException


class TestFootprintApi(unittest.TestCase):
    """FootprintApi unit test stubs"""

    def setUp(self):
        self.api = footprint.api.footprint_api.FootprintApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_copy_user_footprint(self):
        """Test case for copy_user_footprint

        Copy from and existing footprint.  # noqa: E501
        """
        pass

    def test_create_user_footprint(self):
        """Test case for create_user_footprint

        Create new footprint.  # noqa: E501
        """
        pass

    def test_create_user_footprint_region(self):
        """Test case for create_user_footprint_region

        Create new region under an existing footprint.  # noqa: E501
        """
        pass

    def test_delete_user_footprint(self):
        """Test case for delete_user_footprint

        Delete footprint.  # noqa: E501
        """
        pass

    def test_delete_user_footprint_region(self):
        """Test case for delete_user_footprint_region

        Delete a region under an existing footprint.  # noqa: E501
        """
        pass

    def test_find_footprints(self):
        """Test case for find_footprints

        Returns the list of footprints of the user.  # noqa: E501
        """
        pass

    def test_find_user_footprint_regions(self):
        """Test case for find_user_footprint_regions

        Returns the list of the regions of a footprint.  # noqa: E501
        """
        pass

    def test_find_user_footprints(self):
        """Test case for find_user_footprints

        Returns the list of footprints of the user.  # noqa: E501
        """
        pass

    def test_get_user_footprint(self):
        """Test case for get_user_footprint

        Returns the header information of a footprint.  # noqa: E501
        """
        pass

    def test_get_user_footprint_outline(self):
        """Test case for get_user_footprint_outline

        Returns the outline a footprint.  # noqa: E501
        """
        pass

    def test_get_user_footprint_outline_points(self):
        """Test case for get_user_footprint_outline_points

        Returns the points of the outline of a footprint.  # noqa: E501
        """
        pass

    def test_get_user_footprint_region(self):
        """Test case for get_user_footprint_region

        Returns the header information of a region.  # noqa: E501
        """
        pass

    def test_get_user_footprint_region_outline(self):
        """Test case for get_user_footprint_region_outline

        Returns the outline a footprint.  # noqa: E501
        """
        pass

    def test_get_user_footprint_region_outline_points(self):
        """Test case for get_user_footprint_region_outline_points

        Returns the points of the outline of a footprint.  # noqa: E501
        """
        pass

    def test_get_user_footprint_region_shape(self):
        """Test case for get_user_footprint_region_shape

        Returns the shape description of a footprint.  # noqa: E501
        """
        pass

    def test_get_user_footprint_region_thumbnail(self):
        """Test case for get_user_footprint_region_thumbnail

        Get the thumbnail of a footprint.  # noqa: E501
        """
        pass

    def test_get_user_footprint_shape(self):
        """Test case for get_user_footprint_shape

        Returns the shape description of a footprint.  # noqa: E501
        """
        pass

    def test_get_user_footprint_thumbnail(self):
        """Test case for get_user_footprint_thumbnail

        Get the thumbnail of a footprint.  # noqa: E501
        """
        pass

    def test_modify_user_footprint(self):
        """Test case for modify_user_footprint

        Modify existing footprint.  # noqa: E501
        """
        pass

    def test_modify_user_footprint_region(self):
        """Test case for modify_user_footprint_region

        Modify a region under an existing footprint.  # noqa: E501
        """
        pass

    def test_plot_user_footprint(self):
        """Test case for plot_user_footprint

        Plots a footprint  # noqa: E501
        """
        pass

    def test_plot_user_footprint_advanced(self):
        """Test case for plot_user_footprint_advanced

        Plots a footprint, with advanced parameters  # noqa: E501
        """
        pass

    def test_plot_user_footprint_region(self):
        """Test case for plot_user_footprint_region

        Plots a footprint.  # noqa: E501
        """
        pass

    def test_plot_user_footprint_region_advanced(self):
        """Test case for plot_user_footprint_region_advanced

        Plots a footprint.  # noqa: E501
        """
        pass

    def test_set_user_footprint_region_shape(self):
        """Test case for set_user_footprint_region_shape

        Upload region shape binary or other representation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
