# coding: utf-8

"""
    null

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: null
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import footprint
from footprint.models.point import Point  # noqa: E501
from footprint.rest import ApiException


class TestPoint(unittest.TestCase):
    """Point unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPoint(self):
        """Test Point"""
        # FIXME: construct object with mandatory attributes with example values
        # model = footprint.models.point.Point()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
