# coding: utf-8

"""
    null

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: null
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import footprint
from footprint.api.editor_api import EditorApi  # noqa: E501
from footprint.rest import ApiException


class TestEditorApi(unittest.TestCase):
    """EditorApi unit test stubs"""

    def setUp(self):
        self.api = footprint.api.editor_api.EditorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_c_hull_regions(self):
        """Test case for c_hull_regions

        Generate the convex hull of the regions.  # noqa: E501
        """
        pass

    def test_copy_region(self):
        """Test case for copy_region

        Copy a region.  # noqa: E501
        """
        pass

    def test_create_region(self):
        """Test case for create_region

        Create a new region.  # noqa: E501
        """
        pass

    def test_delete_footprint(self):
        """Test case for delete_footprint

        Delete footprint and reset the editor.  # noqa: E501
        """
        pass

    def test_delete_region(self):
        """Test case for delete_region

        Delete a region.  # noqa: E501
        """
        pass

    def test_download_footprint(self):
        """Test case for download_footprint

        Returns the footprint in raw format text or binary.  # noqa: E501
        """
        pass

    def test_download_footprint_outline(self):
        """Test case for download_footprint_outline

        Returns the outline of the footprint.  # noqa: E501
        """
        pass

    def test_download_region(self):
        """Test case for download_region

        Returns the shape description of the footprint region.  # noqa: E501
        """
        pass

    def test_download_region_outline(self):
        """Test case for download_region_outline

        Returns the outline of the footprint.  # noqa: E501
        """
        pass

    def test_get_footprint(self):
        """Test case for get_footprint

        Returns the header information of the edited footprint  # noqa: E501
        """
        pass

    def test_get_footprint_outline_points(self):
        """Test case for get_footprint_outline_points

        Returns the points of the outline of the footprint.  # noqa: E501
        """
        pass

    def test_get_region(self):
        """Test case for get_region

        Returns the header information of a region.  # noqa: E501
        """
        pass

    def test_get_region_outline_points(self):
        """Test case for get_region_outline_points

        Returns the points of the outline of the region.  # noqa: E501
        """
        pass

    def test_grow_region(self):
        """Test case for grow_region

        Grow region.  # noqa: E501
        """
        pass

    def test_intersect_regions(self):
        """Test case for intersect_regions

        Compute the intersection of regions.  # noqa: E501
        """
        pass

    def test_list_regions(self):
        """Test case for list_regions

        List regions.  # noqa: E501
        """
        pass

    def test_modify_footprint(self):
        """Test case for modify_footprint

        Modified the properties of the footprint in the editor.  # noqa: E501
        """
        pass

    def test_modify_region(self):
        """Test case for modify_region

        Modify a region.  # noqa: E501
        """
        pass

    def test_move_region(self):
        """Test case for move_region

        Move a region.  # noqa: E501
        """
        pass

    def test_plot_footprint(self):
        """Test case for plot_footprint

        Plots the footprint  # noqa: E501
        """
        pass

    def test_plot_footprint_advanced(self):
        """Test case for plot_footprint_advanced

        Plots the footprint, with advanced parameters  # noqa: E501
        """
        pass

    def test_plot_region(self):
        """Test case for plot_region

        Plots the region  # noqa: E501
        """
        pass

    def test_plot_region_advanced(self):
        """Test case for plot_region_advanced

        Plots the footprint, with advanced parameters  # noqa: E501
        """
        pass

    def test_subtract_regions(self):
        """Test case for subtract_regions

        Compute the difference of regions.  # noqa: E501
        """
        pass

    def test_union_regions(self):
        """Test case for union_regions

        Compute the union of regions.  # noqa: E501
        """
        pass

    def test_upload_region(self):
        """Test case for upload_region

        Upload a region binary or other representation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
