# coding: utf-8

# flake8: noqa
"""
    null

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: null
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from footprint.models.angle import Angle
from footprint.models.c_hull import CHull
from footprint.models.circle import Circle
from footprint.models.color_theme import ColorTheme
from footprint.models.combination_method import CombinationMethod
from footprint.models.coordinate_representation import CoordinateRepresentation
from footprint.models.coordinate_system import CoordinateSystem
from footprint.models.degree_style import DegreeStyle
from footprint.models.footprint import Footprint
from footprint.models.footprint_request import FootprintRequest
from footprint.models.footprint_response import FootprintResponse
from footprint.models.links import Links
from footprint.models.outline_reduction import OutlineReduction
from footprint.models.plot import Plot
from footprint.models.plot_request import PlotRequest
from footprint.models.point import Point
from footprint.models.poly import Poly
from footprint.models.projection import Projection
from footprint.models.rect import Rect
from footprint.models.region import Region
from footprint.models.region_list_response import RegionListResponse
from footprint.models.region_request import RegionRequest
from footprint.models.region_response import RegionResponse
from footprint.models.rest_error import RestError
from footprint.models.rotation import Rotation
