# coding: utf-8

"""
    SkyQuery REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from footprint.models.angle import Angle  # noqa: F401,E501
from footprint.models.point import Point  # noqa: F401,E501


class Circle(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'center': 'Point',
        'radius': 'Angle'
    }

    attribute_map = {
        'center': 'center',
        'radius': 'radius'
    }

    def __init__(self, center=None, radius=None):  # noqa: E501
        """Circle - a model defined in Swagger"""  # noqa: E501

        self._center = None
        self._radius = None
        self.discriminator = None

        if center is not None:
            self.center = center
        if radius is not None:
            self.radius = radius

    @property
    def center(self):
        """Gets the center of this Circle.  # noqa: E501


        :return: The center of this Circle.  # noqa: E501
        :rtype: Point
        """
        return self._center

    @center.setter
    def center(self, center):
        """Sets the center of this Circle.


        :param center: The center of this Circle.  # noqa: E501
        :type: Point
        """

        self._center = center

    @property
    def radius(self):
        """Gets the radius of this Circle.  # noqa: E501


        :return: The radius of this Circle.  # noqa: E501
        :rtype: Angle
        """
        return self._radius

    @radius.setter
    def radius(self, radius):
        """Sets the radius of this Circle.


        :param radius: The radius of this Circle.  # noqa: E501
        :type: Angle
        """

        self._radius = radius

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Circle):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
