# coding: utf-8

"""
    null

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: null
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from footprint.models.combination_method import CombinationMethod  # noqa: F401,E501
from footprint.models.region import Region  # noqa: F401,E501


class Footprint(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'owner': 'str',
        'name': 'str',
        'combination_method': 'CombinationMethod',
        'comments': 'str',
        'public': 'bool',
        'combined_region': 'Region'
    }

    attribute_map = {
        'owner': 'owner',
        'name': 'name',
        'combination_method': 'combinationMethod',
        'comments': 'comments',
        'public': 'public',
        'combined_region': 'combinedRegion'
    }

    def __init__(self, owner=None, name=None, combination_method=None, comments=None, public=None, combined_region=None):  # noqa: E501
        """Footprint - a model defined in Swagger"""  # noqa: E501

        self._owner = None
        self._name = None
        self._combination_method = None
        self._comments = None
        self._public = None
        self._combined_region = None
        self.discriminator = None

        if owner is not None:
            self.owner = owner
        if name is not None:
            self.name = name
        if combination_method is not None:
            self.combination_method = combination_method
        if comments is not None:
            self.comments = comments
        if public is not None:
            self.public = public
        if combined_region is not None:
            self.combined_region = combined_region

    @property
    def owner(self):
        """Gets the owner of this Footprint.  # noqa: E501


        :return: The owner of this Footprint.  # noqa: E501
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this Footprint.


        :param owner: The owner of this Footprint.  # noqa: E501
        :type: str
        """

        self._owner = owner

    @property
    def name(self):
        """Gets the name of this Footprint.  # noqa: E501


        :return: The name of this Footprint.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Footprint.


        :param name: The name of this Footprint.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def combination_method(self):
        """Gets the combination_method of this Footprint.  # noqa: E501


        :return: The combination_method of this Footprint.  # noqa: E501
        :rtype: CombinationMethod
        """
        return self._combination_method

    @combination_method.setter
    def combination_method(self, combination_method):
        """Sets the combination_method of this Footprint.


        :param combination_method: The combination_method of this Footprint.  # noqa: E501
        :type: CombinationMethod
        """

        self._combination_method = combination_method

    @property
    def comments(self):
        """Gets the comments of this Footprint.  # noqa: E501


        :return: The comments of this Footprint.  # noqa: E501
        :rtype: str
        """
        return self._comments

    @comments.setter
    def comments(self, comments):
        """Sets the comments of this Footprint.


        :param comments: The comments of this Footprint.  # noqa: E501
        :type: str
        """

        self._comments = comments

    @property
    def public(self):
        """Gets the public of this Footprint.  # noqa: E501


        :return: The public of this Footprint.  # noqa: E501
        :rtype: bool
        """
        return self._public

    @public.setter
    def public(self, public):
        """Sets the public of this Footprint.


        :param public: The public of this Footprint.  # noqa: E501
        :type: bool
        """

        self._public = public

    @property
    def combined_region(self):
        """Gets the combined_region of this Footprint.  # noqa: E501


        :return: The combined_region of this Footprint.  # noqa: E501
        :rtype: Region
        """
        return self._combined_region

    @combined_region.setter
    def combined_region(self, combined_region):
        """Sets the combined_region of this Footprint.


        :param combined_region: The combined_region of this Footprint.  # noqa: E501
        :type: Region
        """

        self._combined_region = combined_region

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Footprint):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
