# coding: utf-8

"""
    SkyQuery REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from footprint.models.point import Point  # noqa: F401,E501


class Rect(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'p1': 'Point',
        'p2': 'Point'
    }

    attribute_map = {
        'p1': 'p1',
        'p2': 'p2'
    }

    def __init__(self, p1=None, p2=None):  # noqa: E501
        """Rect - a model defined in Swagger"""  # noqa: E501

        self._p1 = None
        self._p2 = None
        self.discriminator = None

        if p1 is not None:
            self.p1 = p1
        if p2 is not None:
            self.p2 = p2

    @property
    def p1(self):
        """Gets the p1 of this Rect.  # noqa: E501


        :return: The p1 of this Rect.  # noqa: E501
        :rtype: Point
        """
        return self._p1

    @p1.setter
    def p1(self, p1):
        """Sets the p1 of this Rect.


        :param p1: The p1 of this Rect.  # noqa: E501
        :type: Point
        """

        self._p1 = p1

    @property
    def p2(self):
        """Gets the p2 of this Rect.  # noqa: E501


        :return: The p2 of this Rect.  # noqa: E501
        :rtype: Point
        """
        return self._p2

    @p2.setter
    def p2(self, p2):
        """Sets the p2 of this Rect.


        :param p2: The p2 of this Rect.  # noqa: E501
        :type: Point
        """

        self._p2 = p2

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Rect):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
