# coding: utf-8

"""
    null

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: null
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from footprint.models.links import Links  # noqa: F401,E501
from footprint.models.region import Region  # noqa: F401,E501


class RegionListResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'regions': 'list[Region]',
        'links': 'Links'
    }

    attribute_map = {
        'regions': 'regions',
        'links': 'links'
    }

    def __init__(self, regions=None, links=None):  # noqa: E501
        """RegionListResponse - a model defined in Swagger"""  # noqa: E501

        self._regions = None
        self._links = None
        self.discriminator = None

        if regions is not None:
            self.regions = regions
        if links is not None:
            self.links = links

    @property
    def regions(self):
        """Gets the regions of this RegionListResponse.  # noqa: E501


        :return: The regions of this RegionListResponse.  # noqa: E501
        :rtype: list[Region]
        """
        return self._regions

    @regions.setter
    def regions(self, regions):
        """Sets the regions of this RegionListResponse.


        :param regions: The regions of this RegionListResponse.  # noqa: E501
        :type: list[Region]
        """

        self._regions = regions

    @property
    def links(self):
        """Gets the links of this RegionListResponse.  # noqa: E501


        :return: The links of this RegionListResponse.  # noqa: E501
        :rtype: Links
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this RegionListResponse.


        :param links: The links of this RegionListResponse.  # noqa: E501
        :type: Links
        """

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RegionListResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
